### PR TITLE
Advance RxDataBuffer In-Place Instead of Copying

### PR DESCRIPTION
**Pull request by Adlai-Holler**
This should save us some resources.

### CODE REVIEW

**Comment by vkanishk** [comment]
This is not working when tested on Device. Messages are not received.

**Review by vkanishk — CHANGES_REQUESTED** [review]
Thank you for working on this. However, when i test this on device, no messages are received. I am trying to see what needs to be fixed. Can you try as well?

**Comment by Adlai-Holler** [comment]
@vkanishk Hey sorry about that! We needed to remove `packetlen+1` bytes from the front, but I was only removing `packetlen`. Updated.

**Comment by vkanishk** [comment]
@Adlai-Holler The messages are still not received. Can you check again please? Thanks

**Review by RanjaniOS — COMMENTED** [review]
I have checked the code, in this you are setting the "RXDatabuffer" to nil which is not a correct approach. In buffer we are calculating the data length with help of End character. If you do clear the data it will break the whole data link.mThat is why @vkanishk is not getting data. We need to add the left over data to the "RXDatabuffer" which we are already doing.
@emarsman please advise.

**Comment by emarsman** [comment]
Closing.

**Pull request closed without merging**
